name: calibrain
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - mne
  - POT
  - nibabel
  - pyyaml
  - pyvistaqt # for plotting 3D brain surfaces
  - ipywidgets # for interactive widgets in 3D brain surface plotting
  - PyQt5 # for creating the GUI
  - scipy
  - sphinx-autodoc-typehints # for generating documentation with type hints
  - sphinx-copybutton # for adding a "Copy" button to code blocks