[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "calibrain"
version = "0.1.0"
description = "Uncertainty estimation and calibration in EEG/MEG inverse source imaging"
authors = [
    {name = "Ismail Huseynov", email = "ismailhuseynov6666@gmail.com"},
    {name = "Mohammad Orabe", email = "orabe.mhd@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.6"

dependencies = [
    "numpy",
    "pandas",
    # "scipy",
    "scikit-learn",
    "mne",
    #"POT",
    "nibabel",
    "pyyaml",
]

[project.optional-dependencies]
dev = [
    "pytest==6.2.4"
]

[project.scripts]
# Define any CLI scripts here
# calibrain-cli = "calibrain.cli:main"

[project.urls]
Homepage = "https://github.com/braindatalab/CaliBrain"
Repository = "https://github.com/braindatalab/CaliBrain"
Wiki = "https://github.com/braindatalab/CaliBrain/wiki"
# Documentation = "https://calibrain.readthedocs.io/"