# Configuration file for dipole simulation:
# This file is used to set up the parameters for the dipole simulation.
# The parameters are organized into different sections, each with its own set of options.
# The sections include:
# - source_space: Parameters for the source space.
# - bem_model: Parameters for the BEM model.
# - montage: Parameters for the montage.
# - info: Parameters for the info.
# - forward_solution: Parameters for the forward solution.
# - leadfield: Parameters for the leadfield.

# NOTE: The parameters in each section are used to configure the simulation.
# fname: ""  # Leave empty to compute from scratch, or provide a valid file path, then other parameters in this key will be ignored. 

data:
  data_path: "/Users/orabe/0.braindata/MNE-sample-data"
  subject: "fsaverage"
  subjects_dir: "/Users/orabe/0.braindata/MNE-sample-data/subjects"
  save_path: "./results"

source_space:
  fname: "results/fsaverage-src.fif"  # Leave empty to compute from scratch, or provide a valid file path, then other parameters in this key will be ignored. The name of the file should end with ``-src.fif`` or ``-src.fif.gz``.
  spacing: "ico4" # default: "oct6"
  surface: "white"
  add_dist: true
  n_jobs: -1
  save: true # Save the source space to a file. If True, the file name will be ``{subject}-src.fif``.
  overwrite: true  # Overwrite the file if it already exists.
  verbose: false

bem_model:
  fname: "results/fsaverage-bem.fif"  # If provided, other parameters in this key will be ignored.
  # ico: None # The surface ico downsampling to use, e.g. ``5=20484``, ``4=5120``,  ``3=1280``. If None, no subsampling is applied. MNE default is ``4``.
  conductivity: [0.3, 0.006, 0.3] # for 3 layer model.
  solver: "mne"
  save: true # Save the BEM model to a file. If True, the file name will be ``{subject}-bem.fif``.
  overwrite: true  # Overwrite the file if it already exists.
  verbose: false

montage:
  fname: "results/fsaverage-montage.fif"  # If provided, other parameters in this key will be ignored. FIF file from which to read digitization locations.
  kind: "easycap-M43"
  head_size: 0.095
  save: true # Save the montage to a file. If True, the file name will be ``{subject}-montage.fif``.
  overwrite: true  # Overwrite the file if it already exists.
  verbose: false

info:
  fname: "results/fsaverage-info.fif"  # If provided, other parameters in this key will be ignored
  sfreq: 150
  ch_types: "eeg"
  save: true # Save the info to a file. If True, the file name will be ``{subject}-info.fif``.

forward_solution:
  fname: "results/fsaverage-fixed-fwd.fif"  # If provided, other parameters in this key will be ignored. The file name should end with ``{orientation_type}-fwd.fif``, ``{orientation_type}-fwd.fif.gz``,
  trans: "fsaverage"
  eeg: true
  meg: false
  mindist: 0.0
  ignore_ref: false
  n_jobs: -1
  orientation_type: "fixed" #  used for converting the dipole orientation.
  surf_ori: True
  force_fixed: True
  save: true # Save the forward solution to a file. If True, the file name will be ``{subject}-fwd-{orientation_type}.fif``.
  overwrite: true  # Overwrite the file if it already exists.
  verbose: true

leadfield:
  fname: "results/fsaverage-leadfield-fixed.npz" # *_fixed.npz or *_free.npz. File that contains the leadfield matrix must be stored under the key ``leadfield``. Check npz file for the leadfield matrix for more info.
  save: true
  allow_pickle: false